# https://aider.chat/docs/config/aider_conf.html
mini: true # use 4o-mini by default
gitignore: false # added in global gitignore
auto-commits: true # commit, I'll figure out later

# These just looked ugly in the logs
attribute-author: false
attribute-committer: false
