color:
    when: auto
    theme: minimal
size: short
total-size: false
indicators: false
no-symlink: false
icons:
    when: never
date: relative
permission: octal
blocks:
    - permission
    - size
    - date
    - name
symlink-arrow: ->
