# https://github.com/kardolus/chatgpt-cli?tab=readme-ov-file#configuration
name: openai
model: gpt-3.5-turbo
max_tokens: 4096
role: You are a helpful assistant for a software engineer
temperature: 1
top_p: 1
frequency_penalty: 0
presence_penalty: 0
omit_history: false
command_prompt: >
