[model_aliases]
  v3 = "openrouter/deepseek/deepseek-chat-v3-0324:free"
  flash = "openrouter/google/gemini-2.0-flash-exp:free"
  gemini = "openrouter/google/gemini-2.5-pro-exp-03-25:free"
  4o = "openai/gpt-4o"
  mini = "openai/gpt-4o-mini"
  ghmini = "github/gpt-4o-mini"
  o3 = "github/o3-mini"