[[functions]]
name = "set_alarm"
description = "Set an alarm on the system"
command = ",apple-alarm '{{time}}'"

[[functions.parameters]]
name = "time"
type = "string"
description = "Time to set the alarm (HH:mm)"
required = true

[[functions]]
name = "get_datetime"
description = "Get current date and time"
command = "date"

[[functions]]
name = "delete_alarm"
description = "Delete an alarm already based on time"
command = ",alarm-delete '{{time}}'"

[[functions.parameters]]
name = "time"
type = "string"
description = "Time of the alarm to be deleted (HH:mm)"
required = true

[[functions]]
name = "open_website"
description = "Open a website in the default browser"
command = "open '{{url}}'"

[[functions.parameters]]
name = "url"
type = "string"
description = "URL of the website to open"
required = true

[[functions]]
name = "adjust_brightness"
description = "Adjust screen brightness"
command = ",adjust-brightness '{{level}}'"

[[functions.parameters]]
name = "level"
type = "string"
description = "Direction to adjust brightness (increase/decrease)"
required = true

[[functions]]
name = "get_weather"
description = "Get weather forecast for a location"
command = "curl -s wttr.in/{{location}}?format=j1"
safe = true

[[functions.parameters]]
name = "location"
type = "string"
description = "Location to check weather for (If none is provided, current location is used)"
required = false

[[functions]]
name = "send_email"
description = "Send an email"
command = ",send-email \"{{recipient}}\" \"{{subject}}\" \"{{body}}\""

[[functions.parameters]]
name = "recipient"
type = "string"
description = "Recipient email address"
required = true

[[functions.parameters]]
name = "subject"
type = "string"
description = "Email subject (with double quotes escaped)"
required = true

[[functions.parameters]]
name = "body"
type = "string"
description = "Email body (with double quotes escaped)"
required = true

[[functions]]
name = "send_notification"
description = "Send a system notification"
command = "notify \"{{title}}\" \"{{message}}\""

[[functions.parameters]]
name = "title"
type = "string"
description = "Title of the notification (with double quotes escaped)"
required = true

[[functions.parameters]]
name = "message"
type = "string"
description = "Message content of the notification (with double quotes escaped)"
required = true