[user]
name = "Abin Simon"
email = "mail@meain.io"

[ui]
default-command = "log"
pager = ["sh", "-c", "diff-so-fancy | less -RFX"]

[ui.diff]
format = "git"

[colors]
"diff removed token" = { underline = false }
"diff added token" = { underline = false }

[revset-aliases]
"stack(r)" = "r | ancestors(descendants(immutable_heads()..r), 2)"

[aliases]
stack = ["log", "-r", "stack(@)"]
[templates]
log = 'personal_log_oneline'

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'

# Refer to jj/cli/src/config/templates.toml
personal_log_oneline = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        format_short_change_id_with_hidden_and_divergent_info(self),
        if(bookmarks, "[" ++ bookmarks ++ "]"),
        tags,
        working_copies,
        if(git_head, label("git_head", "HEAD")),
        if(conflict, label("conflict", "conflict")),
        if(empty, label("empty", "(empty)")),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
      ) ++ "\n",
    ),
  )
)
'''